### PR TITLE
Added `min_metacluster_size_frac`

### PR DESCRIPTION
**Pull request by Avsecz**
Added an alternative way to specify the minimal number of seqlets per metacluster. It kicks in when the number of seqlets is large and `min_metacluster_size` doesn't work. I will merge in the master into this branch if it makes sense to merge into master.

### CODE REVIEW

**Comment by AvantiShri** [comment]
Where is min_metacluster_size used? We have a max_metacluster_size, but when I ctrl+f for min_metacluster_size I don’t see that argument being passed into anything - am I missing something?

**Comment by AvantiShri** [comment]
Oh never mind found it - I remember now. Was viewing this on phone so didn’t see it. Yes this edit absolutely makes sense.

**Comment by AvantiShri** [comment]
Can you increment the version number? Then it would be good to merge

**Comment by Avsecz** [comment]
done. bumped the version to `0.5.0.1`.

**Pull request merged**
